//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.11 at 05:28:45 PM IDT 
//


package com.example.me;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.me package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.me
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetBundleRequest }
     * 
     */
    public GetBundleRequest createGetBundleRequest() {
        return new GetBundleRequest();
    }

    /**
     * Create an instance of {@link GetBundleResponse }
     * 
     */
    public GetBundleResponse createGetBundleResponse() {
        return new GetBundleResponse();
    }

    /**
     * Create an instance of {@link Bundle }
     * 
     */
    public Bundle createBundle() {
        return new Bundle();
    }

    /**
     * Create an instance of {@link AddBundleRequest }
     * 
     */
    public AddBundleRequest createAddBundleRequest() {
        return new AddBundleRequest();
    }

    /**
     * Create an instance of {@link AddBundleResponse }
     * 
     */
    public AddBundleResponse createAddBundleResponse() {
        return new AddBundleResponse();
    }

}
